flowchart LR
    ProcMacros[Rust + proc-macros] --> Metadata[Metadata]
    UDL[UDL] --> Metadata[Metadata]
    Metadata --> InitialIr[Initial IR]
    InitialIr --> GeneralIr[General IR]
    GeneralIr --> KotlinIr[Kotlin IR]
    GeneralIr --> SwiftIr[Swift IR]
    GeneralIr --> PythonIr[Python IR]
    GeneralIr --> RubyIr[Ruby IR]

    subgraph Not yet implemented
    KotlinIr --> Kotlin[Generated Kotlin]
    SwiftIr --> Swift[Generated Swift]
    PythonIr --> Python[Generated Python]
    RubyIr --> Ruby[Generated Ruby]
    end
