block-beta
  columns 2
  block:JsLayer
    columns 1
    GeckoJsTitle["uniffi-bindgen-gecko-js"]
    Js["JS Layer"]
    space
    Cpp["C++ Layer"]
  end
  block:UserLayer
    columns 1
    UserCodeTitle["User code"]
    RustUser["Rust user function"]
  end
  block:ScaffoldingLayer:2
    columns 2
    space
    UniffiBindgenTitle["uniffi-bindgen"]
    Rust["Rust Scaffolding"]
    space
  end

  Js --"Lower"--> Cpp
  Cpp --"Lower"--> Rust
  Rust --"Lift"--> RustUser

classDef default stroke:transparent,fill:#fff
classDef layer stroke:#c0c0c0,fill:#cae9ff
classDef title stroke:transparent,fill:transparent,color:#f72585
classDef invisible stroke:transparent,fill:transparent
class JsLayer layer
class ScaffoldingLayer layer
class UserLayer layer
class GeckoJsTitle title
class UniffiBindgenTitle title
class UserCodeTitle title
